// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:

import { CurrencyCode, Transaction } from "@/data/types";
import { v4 as uuid } from "uuid";

const transactions: Transaction[] = [
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-06-15"),
    is_positive: true,
    amount_cents: 5000,
    currency_code: CurrencyCode.USD,
    description: "Payment from Evil Rabbit",
    category: "Food",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-06-16"),
    is_positive: true,
    amount_cents: 10050,
    currency_code: CurrencyCode.USD,
    description: "Payment from Delba de Oliveira",
    category: "Food",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-06-16"),
    is_positive: true,
    amount_cents: 20000,
    currency_code: CurrencyCode.USD,
    description: "Payment from Lee Robinson",
    category: "Transport",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-06-17"),
    is_positive: true,
    amount_cents: 10000,
    currency_code: CurrencyCode.USD,
    description: "Uniqlo",
    category: "Shopping",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-07-01"),
    is_positive: true,
    amount_cents: 15000,
    currency_code: CurrencyCode.USD,
    description: "Payment from John Doe",
    category: "Food",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-07-02"),
    is_positive: true,
    amount_cents: 8000,
    currency_code: CurrencyCode.USD,
    description: "Payment from Jane Smith",
    category: "Transport",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-05-15"),
    is_positive: true,
    amount_cents: 12000,
    currency_code: CurrencyCode.USD,
    description: "Payment from Bob Johnson",
    category: "Food",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-05-16"),
    is_positive: true,
    amount_cents: 25000,
    currency_code: CurrencyCode.USD,
    description: "Payment from Alice Brown",
    category: "Shopping",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-07-01"),
    is_positive: true,
    amount_cents: 5000,
    currency_code: CurrencyCode.USD,
    description: "Payment from John Doe",
    category: "Food",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-07-02"),
    is_positive: true,
    amount_cents: 10000,
    currency_code: CurrencyCode.USD,
    description: "Payment from Jane Smith",
    category: "Transport",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-07-03"),
    is_positive: true,
    amount_cents: 15000,
    currency_code: CurrencyCode.USD,
    description: "Payment from John Doe",
    category: "Food",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-07-04"),
    is_positive: true,
    amount_cents: 8000,
    currency_code: CurrencyCode.USD,
    description: "Payment from Jane Smith",
    category: "Transport",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-07-05"),
    is_positive: true,
    amount_cents: 12000,
    currency_code: CurrencyCode.USD,
    description: "Payment from Bob Johnson",
    category: "Food",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-07-06"),
    is_positive: true,
    amount_cents: 25000,
    currency_code: CurrencyCode.USD,
    description: "Payment from Alice Brown",
    category: "Shopping",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-07-07"),
    is_positive: true,
    amount_cents: 5000,
    currency_code: CurrencyCode.USD,
    description: "Payment from John Doe",
    category: "Food",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-07-08"),
    is_positive: true,
    amount_cents: 10000,
    currency_code: CurrencyCode.USD,
    description: "Payment from Jane Smith",
    category: "Transport",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-07-09"),
    is_positive: true,
    amount_cents: 15000,
    currency_code: CurrencyCode.USD,
    description: "Payment from John Doe",
    category: "Food",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-07-10"),
    is_positive: true,
    amount_cents: 8000,
    currency_code: CurrencyCode.USD,
    description: "Payment from Jane Smith",
    category: "Transport",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-07-11"),
    is_positive: true,
    amount_cents: 12000,
    currency_code: CurrencyCode.USD,
    description: "Payment from Bob Johnson",
    category: "Food",
  },
  {
    uuid: uuid(),
    timestamp_utc: new Date("2024-07-12"),
    is_positive: true,
    amount_cents: 25000,
    currency_code: CurrencyCode.USD,
    description: "Payment from Alice Brown",
    category: "Shopping",
  },
];

export { transactions };
